In [2]:
import os
os.listdir()

['HousingData.csv', '.ipynb_checkpoints', 'Untitled2.ipynb']

In [3]:
# import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# plot graph 
%matplotlib inline

In [5]:
# import the dataset
data = pd.read_csv('HousingData.csv')
data

Purchase time passed(1990)  Pricing
0                          1.1    39343
1                          1.2    46205
2                          1.5    37731
3                          2.0    43525
4                          2.2    39891
5                          2.8    56642
6                          3.0    60150
7                          3.2    54445
8                          3.3    64445
9                          3.8    57189
10                         3.9    63218
11                         4.0    55794
12                         4.1    56957
13                         4.2    57081
14                         4.5    61111
15                         4.9    67938
16                         5.1    66029
17                         5.5    83088
18                         5.9    81363
19                         6.0    93940
20                         6.8    91738
21                         7.3    98273
22                         7.9   101000
23                         8.2   113122
24                         8.7   109211
25                         9.0   105311
26                         9.5   116611
27                         9.6   112422
28                        10.3   122432
29                        10.5   123322

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Purchase time passed(1990)  30 non-null     float64
 1   Pricing                     30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes


In [7]:
# create two matrix for dependent and independent values
X = data.iloc[: , :-1].values
y = data.iloc[: , 1]

In [8]:
X

array([[ 1.1],
       [ 1.2],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.8],
       [ 3. ],
       [ 3.2],
       [ 3.3],
       [ 3.8],
       [ 3.9],
       [ 4. ],
       [ 4.1],
       [ 4.2],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.5],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.3],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [9]:
y

0      39343
1      46205
2      37731
3      43525
4      39891
5      56642
6      60150
7      54445
8      64445
9      57189
10     63218
11     55794
12     56957
13     57081
14     61111
15     67938
16     66029
17     83088
18     81363
19     93940
20     91738
21     98273
22    101000
23    113122
24    109211
25    105311
26    116611
27    112422
28    122432
29    123322
Name: Pricing, dtype: int64

In [10]:
# prepare test and training data set
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [13]:
X_test

array([[7.9],
       [7.3],
       [9.5],
       [4.9],
       [3.8],
       [4.2],
       [6. ],
       [6.8],
       [1.5]])

In [14]:
y_test

22    101000
21     98273
26    116611
15     67938
9      57189
13     57081
19     93940
20     91738
2      37731
Name: Pricing, dtype: int64

In [15]:
# features scaling is USUALLY not required in Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
regressor = LinearRegression()

In [19]:
regressor.fit(X_train, y_train)

LinearRegression()

In [20]:
# create a predictor so that it can predict
y_predictor = regressor.predict(X_test)

In [22]:
# this is a dummy dataset
y_predictor

array([ 99397.1807114 ,  93902.5634629 , 114049.49337409,  71924.09446887,
        61850.62951328,  65513.70767895,  81997.55942447,  89323.71575581,
        40787.93006067])