# Excercise file for NumPy

In [1]:
myList = [1,2,3,4,5]

In [2]:
myList

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [6]:
myOneDArray = np.array(myList)

In [7]:
myOneDArray

array([1, 2, 3, 4, 5])

In [8]:
myMultiList = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [9]:
myTwoDArray = np.array(myMultiList)

In [10]:
myTwoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 15 points between 0 and 5 equally spaced

In [19]:
np.linspace(0, 5, 15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

### Identity matrix

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Uniform distribution

In [21]:
np.random.rand(5, 5)

array([[0.2627465 , 0.61065388, 0.79147431, 0.59024213, 0.41039828],
       [0.11631755, 0.61444566, 0.06049042, 0.4371037 , 0.71065293],
       [0.43178959, 0.23310752, 0.95691   , 0.62802371, 0.04280715],
       [0.24072161, 0.5328651 , 0.7796782 , 0.41251697, 0.10931524],
       [0.69729698, 0.54929889, 0.8809977 , 0.05655304, 0.24195262]])

### Normal distribution

In [25]:
np.random.randn(5, 5)

array([[-1.34817072,  0.16979044, -0.2782306 , -1.79500005,  0.16733329],
       [ 0.18616268, -0.13082753, -1.53678483,  0.32171706,  0.13088348],
       [-0.50496798, -1.18263803, -0.56987398, -2.07402652, -0.3481158 ],
       [-0.86912756,  1.0405461 , -0.0350531 , -1.07748827, -0.68568963],
       [-1.2676081 ,  0.66007451,  1.37129176, -1.39070788,  1.73921849]])

### Integer based distribution: generates random number

In [26]:
np.random.randint(1, 50)

45

 ## Reshaped

In [27]:
myNum = np.arange(25)

In [28]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
myReshaped = myNum.reshape(5,5)

In [30]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
wrongReshaped = myNum.reshape(6,6)

ValueError: cannot reshape array of size 25 into shape (6,6)