In [2]:
import numpy as np

In [3]:
myArray = np.arange(2, 20)

In [4]:
myArray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
myArray[myArray > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
myArray > 10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [7]:
myArray + myArray

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [8]:
np.sqrt(myArray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])