In [1]:
import os

In [2]:
print(os.listdir())

['.ipynb_checkpoints', 'Social_Network_Ads.csv', 'SVM.ipynb']


In [3]:
# import useful libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# get graphs inline
%matplotlib inline

In [4]:
# load up the data file
data = pd.read_csv('Social_Network_Ads.csv')

In [5]:
# check info about data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
# split our dataset
X = data.iloc[:, [2,3]].values
y = data.iloc[:, [4]].values

In [8]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [9]:
# split it into training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
X_test

array([[    31,  66000],
       [    39, 134000],
       [    23,  20000],
       [    46,  88000],
       [    28,  44000],
       [    34,  43000],
       [    27,  58000],
       [    38, 112000],
       [    43, 133000],
       [    35,  60000],
       [    32, 150000],
       [    28,  37000],
       [    35,  23000],
       [    31,  58000],
       [    36, 118000],
       [    35,  25000],
       [    48,  41000],
       [    28,  84000],
       [    27,  17000],
       [    26,  16000],
       [    42,  73000],
       [    28,  55000],
       [    40,  57000],
       [    52, 150000],
       [    25,  79000],
       [    47, 107000],
       [    39,  71000],
       [    58,  47000],
       [    41,  79000],
       [    37, 137000],
       [    35,  75000],
       [    49,  39000],
       [    26,  30000],
       [    33,  60000],
       [    27,  54000],
       [    37,  71000],
       [    36,  60000],
       [    39,  42000],
       [    48, 131000],
       [    30,  49000],


In [11]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_test

array([[-0.62605741, -0.07158459],
       [ 0.13460086,  2.01926204],
       [-1.38671568, -1.48598084],
       [ 0.80017684,  0.60486579],
       [-0.91130426, -0.74803497],
       [-0.34081056, -0.77878272],
       [-1.00638654, -0.31756655],
       [ 0.03951857,  1.34281166],
       [ 0.51492999,  1.98851429],
       [-0.24572828, -0.25607106],
       [-0.53097513,  2.51122595],
       [-0.91130426, -0.96326919],
       [-0.24572828, -1.39373761],
       [-0.62605741, -0.31756655],
       [-0.15064599,  1.52729812],
       [-0.24572828, -1.33224212],
       [ 0.99034141, -0.84027821],
       [-0.91130426,  0.48187481],
       [-1.00638654, -1.57822408],
       [-1.10146883, -1.60897182],
       [ 0.41984771,  0.14364962],
       [-0.91130426, -0.40980978],
       [ 0.22968314, -0.34831429],
       [ 1.37067054,  2.51122595],
       [-1.19655111,  0.32813609],
       [ 0.89525912,  1.18907293],
       [ 0.13460086,  0.08215413],
       [ 1.94116424, -0.65579174],
       [ 0.32476542,

In [14]:
# implement SVM
from sklearn.svm import SVC

In [15]:
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train.ravel())

SVC(kernel='linear')

In [16]:
# just predict
y_predictor = classifier.predict(X_test)

In [17]:
y_predictor

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [18]:
# confusion matrix
from sklearn.metrics import confusion_matrix
errors = confusion_matrix(y_test, y_predictor)

In [19]:
errors

array([[46,  7],
       [ 2, 25]])