In [1]:
import os

In [2]:
print(os.listdir())

['.ipynb_checkpoints', 'Social_Network_Ads.csv', 'SVM.ipynb']


In [3]:
# import useful libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# get graphs inline
%matplotlib inline

In [4]:
# load up the data file
data = pd.read_csv('Social_Network_Ads.csv')

In [5]:
# check info about data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
# split our dataset
X = data.iloc[:, [2,3]].values
y = data.iloc[:, [4]].values

In [8]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [9]:
# split it into training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
X_test

array([[    33,  28000],
       [    48,  33000],
       [    39,  71000],
       [    25,  90000],
       [    46,  59000],
       [    23,  66000],
       [    46, 117000],
       [    27,  17000],
       [    33, 113000],
       [    19,  76000],
       [    57,  26000],
       [    38,  61000],
       [    38, 113000],
       [    41,  79000],
       [    31,  66000],
       [    41,  30000],
       [    57, 122000],
       [    47,  34000],
       [    27, 137000],
       [    21,  72000],
       [    41,  52000],
       [    27,  31000],
       [    35,  75000],
       [    22,  27000],
       [    37,  62000],
       [    35,  39000],
       [    33,  43000],
       [    38,  50000],
       [    32,  18000],
       [    28,  85000],
       [    42, 149000],
       [    41,  72000],
       [    32, 100000],
       [    37,  33000],
       [    35,  60000],
       [    42, 108000],
       [    54,  26000],
       [    39,  71000],
       [    35, 147000],
       [    49, 141000],


In [11]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_test

array([[-0.46072851, -1.23469291],
       [ 0.95962912, -1.08596832],
       [ 0.10741455,  0.04433852],
       [-1.21825258,  0.60949194],
       [ 0.77024811, -0.31260049],
       [-1.40763359, -0.10438607],
       [ 0.77024811,  1.41260469],
       [-1.02887156, -1.56188699],
       [-0.46072851,  1.29362502],
       [-1.78639563,  0.1930631 ],
       [ 1.8118437 , -1.29418274],
       [ 0.01272404, -0.25311065],
       [ 0.01272404,  1.29362502],
       [ 0.29679556,  0.28229785],
       [-0.65010952, -0.10438607],
       [ 0.29679556, -1.17520307],
       [ 1.8118437 ,  1.56132928],
       [ 0.86493862, -1.05622341],
       [-1.02887156,  2.00750303],
       [-1.59701461,  0.07408343],
       [ 0.29679556, -0.5208149 ],
       [-1.02887156, -1.14545816],
       [-0.27134749,  0.16331818],
       [-1.5023241 , -1.26443782],
       [-0.08196647, -0.22336573],
       [-0.27134749, -0.90749882],
       [-0.46072851, -0.78851915],
       [ 0.01272404, -0.58030474],
       [-0.55541901,